### PR TITLE
functional: add new tests TestUnit{Submit,Load,Start}Replace 

### PR DESCRIPTION
**Pull request by dongsupark**
- TestUnitSubmitReplace() tests whether a command "fleetctl submit --replace hello.service" works or not.
- TestUnitLoadReplace() tests whether a command "fleetctl load --replace hello.service" works or not.
- TestUnitStartReplace() tests whether a command "fleetctl start --replace hello.service" works or not.

This PR depends on #18.
/cc @tixxdz

### CODE REVIEW

**Comment by dongsupark** [comment]
All right. Jenkins job fails, because one of the new tests occasionally fails after running `fleetctl destroy`. I'm not sure why.

**Comment by dongsupark** [comment]
I fixed bugs in the functional tests. Used `maxAttempts` correctly, and fixed the logic error upon retrying `fleetctl destroy`.
Now functional tests are working, and Jenkins job succeeds.
Though I don't like this ugly code. I'm thinking about how to refactor it.

**Comment by dongsupark** [comment]
Did refactoring for the entire patchset. Functional tests are working well too.
@tixxdz if you think it's ok, can you merge this to your tree, to create a PR to the upstream?

**Comment by tixxdz** [comment]
@dongsupark ok just let me know when you add those "submit load and start many units" tests, I'll pull them on top. Thank you!

**Comment by dongsupark** [comment]
Close in favor of https://github.com/coreos/fleet/pull/1509

**Pull request closed without merging**
